/**
 * PhotoRoom API
 * The power of PhotoRoom, automated.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-help@photorom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RemoveBackground200Response model module.
 * @module model/RemoveBackground200Response
 * @version 1.0.0
 */
class RemoveBackground200Response {
    /**
     * Constructs a new <code>RemoveBackground200Response</code>.
     * @alias module:model/RemoveBackground200Response
     * @param base64img {String} 
     */
    constructor(base64img) { 
        
        RemoveBackground200Response.initialize(this, base64img);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, base64img) { 
        obj['base64img'] = base64img;
    }

    /**
     * Constructs a <code>RemoveBackground200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RemoveBackground200Response} obj Optional instance to populate.
     * @return {module:model/RemoveBackground200Response} The populated <code>RemoveBackground200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RemoveBackground200Response();

            if (data.hasOwnProperty('base64img')) {
                obj['base64img'] = ApiClient.convertToType(data['base64img'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RemoveBackground200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RemoveBackground200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RemoveBackground200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['base64img'] && !(typeof data['base64img'] === 'string' || data['base64img'] instanceof String)) {
            throw new Error("Expected the field `base64img` to be a primitive type in the JSON string but got " + data['base64img']);
        }

        return true;
    }


}

RemoveBackground200Response.RequiredProperties = ["base64img"];

/**
 * @member {String} base64img
 */
RemoveBackground200Response.prototype['base64img'] = undefined;






export default RemoveBackground200Response;

