/**
 * PhotoRoom API
 * The power of PhotoRoom, automated.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api-help@photorom.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AccountDetails200Response from './model/AccountDetails200Response';
import AccountDetails200ResponseCredits from './model/AccountDetails200ResponseCredits';
import EditImageBadRequest from './model/EditImageBadRequest';
import EditImageBadRequestError from './model/EditImageBadRequestError';
import FieldMissingError from './model/FieldMissingError';
import FieldMissingError1 from './model/FieldMissingError1';
import FieldMissingError1Error from './model/FieldMissingError1Error';
import FieldMissingError2 from './model/FieldMissingError2';
import FieldMissingError2Error from './model/FieldMissingError2Error';
import FieldMissingError3 from './model/FieldMissingError3';
import FieldMissingError3Error from './model/FieldMissingError3Error';
import FieldMissingError4 from './model/FieldMissingError4';
import FieldMissingError4Error from './model/FieldMissingError4Error';
import PaymentError from './model/PaymentError';
import PaymentErrorError from './model/PaymentErrorError';
import RemoveBackground200Response from './model/RemoveBackground200Response';
import UnknownError from './model/UnknownError';
import UnknownErrorError from './model/UnknownErrorError';
import DefaultApi from './api/DefaultApi';


/**
* The power of PhotoRoom, automated..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var PhotoRoomApi = require('index'); // See note below*.
* var xxxSvc = new PhotoRoomApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new PhotoRoomApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new PhotoRoomApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new PhotoRoomApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AccountDetails200Response model constructor.
     * @property {module:model/AccountDetails200Response}
     */
    AccountDetails200Response,

    /**
     * The AccountDetails200ResponseCredits model constructor.
     * @property {module:model/AccountDetails200ResponseCredits}
     */
    AccountDetails200ResponseCredits,

    /**
     * The EditImageBadRequest model constructor.
     * @property {module:model/EditImageBadRequest}
     */
    EditImageBadRequest,

    /**
     * The EditImageBadRequestError model constructor.
     * @property {module:model/EditImageBadRequestError}
     */
    EditImageBadRequestError,

    /**
     * The FieldMissingError model constructor.
     * @property {module:model/FieldMissingError}
     */
    FieldMissingError,

    /**
     * The FieldMissingError1 model constructor.
     * @property {module:model/FieldMissingError1}
     */
    FieldMissingError1,

    /**
     * The FieldMissingError1Error model constructor.
     * @property {module:model/FieldMissingError1Error}
     */
    FieldMissingError1Error,

    /**
     * The FieldMissingError2 model constructor.
     * @property {module:model/FieldMissingError2}
     */
    FieldMissingError2,

    /**
     * The FieldMissingError2Error model constructor.
     * @property {module:model/FieldMissingError2Error}
     */
    FieldMissingError2Error,

    /**
     * The FieldMissingError3 model constructor.
     * @property {module:model/FieldMissingError3}
     */
    FieldMissingError3,

    /**
     * The FieldMissingError3Error model constructor.
     * @property {module:model/FieldMissingError3Error}
     */
    FieldMissingError3Error,

    /**
     * The FieldMissingError4 model constructor.
     * @property {module:model/FieldMissingError4}
     */
    FieldMissingError4,

    /**
     * The FieldMissingError4Error model constructor.
     * @property {module:model/FieldMissingError4Error}
     */
    FieldMissingError4Error,

    /**
     * The PaymentError model constructor.
     * @property {module:model/PaymentError}
     */
    PaymentError,

    /**
     * The PaymentErrorError model constructor.
     * @property {module:model/PaymentErrorError}
     */
    PaymentErrorError,

    /**
     * The RemoveBackground200Response model constructor.
     * @property {module:model/RemoveBackground200Response}
     */
    RemoveBackground200Response,

    /**
     * The UnknownError model constructor.
     * @property {module:model/UnknownError}
     */
    UnknownError,

    /**
     * The UnknownErrorError model constructor.
     * @property {module:model/UnknownErrorError}
     */
    UnknownErrorError,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
